### ISSUE TITLE
☂️  Roadmap

### ISSUE THREAD

**Issue by jbee37142** [toss/h6s#112]
## Packages

- [x] #164
  - [x] Support merge colSpan
  - [x] Support merge rowSpan
  - [x] [@h6s/table] Support updateHeader feature
  - [x] [@h6s/table] Support displayValue
  - [x] [@h6s/table] Support footer interface
  - [x] [@h6s/table] Add document
  - [x] [@h6s/table] Add Storybook
  - [x] [@h6s/table] Add Examples

## Common Package

- [x] #131
- [x] #144
- [x] #145
  - https://github.com/actions/setup-node
- [ ] [Common] 🛠 Add test coverage and github-action bot
- [ ] #148

## Website

- [x] [Website] 🎨  Design OpenGraph Image #113 
- [ ] [Website] 🎁  @docusaurus/api-extractor-plugin
  - https://api-extractor.com/
- [ ] [Website] 🎁  @docusaurus/sandpack-plugin
  - https://github.com/codesandbox/sandpack
- [x] #137
  - https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics
- [x] [Website] 🛠  SEO
- [ ] [Website] 🛠  Add search engine (algolia)
- [ ] [Website] 📄  Build main page contents (introduce package examples?, remind section)

## Storybook

- [x] #149
- [ ] [Storybook] 🛠  Add addons for testing

## Examples

- [ ] [Examples] 🛠  SEO

## Org

- [x] 🛠  Security setting
- [x] 🛠  renovate setting #114 
- [x] 🎨  Add GitHub Repository OpenGraph Image #113 
- [x] [Org] 📄  Add contributing guide
- [x] [Org] 📄  Add issue templates
- [x] [Org] 📄  Add pull request templates
- [x] [Org] 📄  Add Code of Conduct document
